spring:
  #连接池配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cskaoyanmall?serverTimezone=GMT
    username: root
    password: 123456
  #druid监控配置
#    druid:
#      filters: stat,wall,log4j,config
#      max-active: 100
#      initial-size: 1
#      max-wait: 60000
#      min-idle: 1
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: select 'x'
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: true
#      max-open-prepared-statements: 50
#      max-pool-prepared-statement-per-connection-size: 20
#      logSlowSql: true
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #json日期格式处理
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#端口号
server:
  port: 80
#分页工具
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: =countSql


